### ISSUE TITLE
Statement about where OCaml-TLS began

### ISSUE THREAD

**Issue by amirmc** [ocamllabs/furore#1]
In `community-and-outreach.md` from commit https://github.com/ocamllabs/furore/commit/0c24edd0b24e5be3519080bc4a288a57fcb87e09: 
"Hannes Mehnert and David Kaloper started the [OCaml-TLS](https://mirage.io/blog/introducing-ocaml-tls) project here in Morocco back in 2014"  (where 'here' refers to the Riad in Marrakech for the Hackathon -- Priscilla).

Is this accurate? I thought it began in Mirleft. See https://mirage.io/blog/ocaml-tls-api-internals-attacks-mitigation#Acknowledgements

**Comment by hannesm** [comment]
OCaml-TLS was started at aftas beach house in mirleft, southern morocco. https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fstatic.panoramio.com%2Fphotos%2Flarge%2F7236829.jpg&f=1

**Comment by GemmaG** [comment]
Yay, thanks for reading it and creating an issue!

How about:
"OCaml Labs sponsored the first MirageOS hackathon - an international, community-organised event - at [Rihad Priscilla](http://queenofthemedina.com/en/index.html) in Marrakech, which provided a perfect venue for community building and hacking. Hannes Mehnert and David Kaloper started the [OCaml-TLS](https://mirage.io/blog/introducing-ocaml-tls) project at a beach house in Mirleft back in 2014, and were keen to encourage others to experience Morocco for themselves."

Is the photo you linked to yours and can I link to it in the report?

**Comment by hannesm** [comment]
sounds good to me!  you can link to:
- https://mirage.io/graphics/aftas-mirleft.jpg
- https://berlin.ccc.de/~hannes/aftas2017.jpg (Aftas beach in january 2017, taken by myself)

**Comment by GemmaG** [comment]
Edited and added links
